spring:
  application:
    name: clothing-sell-website
  datasource:
    url: "jdbc:sqlserver://;serverName=localhost;databaseName=FASHIONSHOP;encrypt=true;trustServerCertificate=true"
    driver-class-name: "com.microsoft.sqlserver.jdbc.SQLServerDriver"
    username: sa
    password: 123456
server:
  port: 8080
  servlet:
    context-path: /clothing-sell
