spring:
  application:
    name: clothing-sell-website
  datasource:
    url: "jdbc:sqlserver://;serverName=localhost;databaseName=FASHIONSHOP;encrypt=true;trustServerCertificate=true"
    driver-class-name: "com.microsoft.sqlserver.jdbc.SQLServerDriver"
    username: sa
    password: 123456

  mail:
    host: smtp.gmail.com
    port: 587
    username: automailsender111@gmail.com
    password: cchp fuat gdtn ayhv
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    default-encoding: UTF-8
  thymeleaf: # Thymeleaf
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: classpath:/templates/

server:
  port: 8080
  servlet:
    context-path: /clothing-sell