spring:
  application:
    name: clothing-sell-website
  datasource:
    url: "jdbc:sqlserver://;serverName=localhost;databaseName=FASHIONSHOP;encrypt=true;trustServerCertificate=true"
    driver-class-name: "com.microsoft.sqlserver.jdbc.SQLServerDriver"
    username: sa
    password: 123456

  thymeleaf: # Thymeleaf
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: file:src/main/resources/templates/

server:
  port: 8080
  servlet:
    context-path: /clothing-sell
